repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: ["--in-place",  "--imports=fillname", "--ignore-init-module-imports", "--remove-unused-variables"]
      exclude: ^.github/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^.github/

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        exclude: ^.github/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      exclude: ^.github/
